### ISSUE TITLE
Not pulling up data or notes on Mimic. 

### ISSUE THREAD

**Issue by SnazzyJazzington** [wolfcomp/MonsterDex#190]
### Mob Id

0 - Mimic

### Content Type

Deep Dungeon (PoTD)

### What threat level sould the mob have

Caution

### What agro type does the mob have

Proximity

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

### Additional mob text guide

Should be noted that it will give a DOT that will last 10min if not killed quickly or interrupted.

**Comment by wolfcomp** [comment]
All mimics have text data, there is just something with how grabbing the target that sometimes fails, and I'm uncertain why it happens. The tell is when ever the ID is 0 in the debug view that something is wrong, currently can't fully reproduce all the time so probably won't be fixing this until after DT is released.

**Comment by wolfcomp** [comment]
This bug of mobs giving the ID of 0 should be fixed in 2.11.0
