### ISSUE TITLE
0 - Blackening Marketeer

### ISSUE THREAD

**Issue by StarkITA** [wolfcomp/MonsterDex#191]
### Mob Id

0 - Blackening Marketeer

### Content Type

TreasureHuntDungeon

### What threat level sould the mob have

Easy

### What agro type does the mob have

I think sight/proximity

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

**Comment by wolfcomp** [comment]
Ref: #190
