### ISSUE TITLE
Missing Pygmaioi

### ISSUE THREAD

**Issue by jcyu46** [wolfcomp/MonsterDex#194]
### Mob Id

0 - Pygmaioi

### Content Type

TreasureHuntDungeon

### What threat level sould the mob have

Easy

### What agro type does the mob have

None

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

**Comment by wolfcomp** [comment]
Ref: #190
