### ISSUE TITLE
PotD rare spawn (no entry)

### ISSUE THREAD

**Issue by INSYG** [wolfcomp/MonsterDex#195]
### Mob Id

0 - Blackening Marketeer

### Content Type

TreasureHuntDungeon

### What threat level sould the mob have

Easy

### What agro type does the mob have

Proximity

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [X] Undead

**Comment by wolfcomp** [comment]
Ref: #190
