### ISSUE TITLE
Adding Meracydian Clone info after first encounter

### ISSUE THREAD

**Issue by Ephirion** [wolfcomp/MonsterDex#197]
### Mob Id

0 - Meracydian Clone

### Content Type

TreasureHuntDungeon

### What threat level sould the mob have

Dangerous

### What agro type does the mob have

Sight

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

### Additional mob text guide

Damage buff. Extremely painful autos

**Comment by wolfcomp** [comment]
Ref: #190
