### ISSUE TITLE
Error message when not in Deep Dungeon

### ISSUE THREAD

**Issue by captaincbr1** [wolfcomp/MonsterDex#199]
### Mob Id

13429 - Ousted Asterodia

### Content Type

DeepDungeon

### What threat level sould the mob have

None

### What agro type does the mob have

None

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

### Additional mob text guide

These mobs are ion Heritage found, so this should not be displayed outside of DD

**Comment by wolfcomp** [comment]
If you don't want to see these, configure the plugin.
