### ISSUE TITLE
Demi-Cochma doesnt seem to be documented

### ISSUE THREAD

**Issue by Oltro15** [wolfcomp/MonsterDex#203]
### Mob Id

12324 - Demi-Cochma

### Content Type

DeepDungeon

### What threat level sould the mob have

Vicious

### What agro type does the mob have

None

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

### Additional mob text guide

This enemy should be avoided.  The auto attacks will kill you when its in range and it has a lot of health. Encountered as early as floor 1

**Comment by Oltro15** [comment]
Its a dread beast so its easy to spot but isnt documented

**Comment by wolfcomp** [comment]
Seems like certain files might not be loaded, need to check further into but won't have time before savage.
