### ISSUE TITLE
Mimic

### ISSUE THREAD

**Issue by Dreamcypher** [wolfcomp/MonsterDex#205]
### Mob Id

2566 - Mimic

### Content Type

DeepDungeon

### What threat level sould the mob have

Caution

### What agro type does the mob have

Proximity

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

### Additional mob text guide

Beware of Infatuation, it gives the Pox debuff, a DoT that stops your regen out of battle.

**Comment by wolfcomp** [comment]
Seems to be related to #203 as it has the data in the files.
