### ISSUE TITLE
Mandragora - if using Pomander of Alteration

### ISSUE THREAD

**Issue by HumonGousPhil** [wolfcomp/MonsterDex#206]
### Mob Id

5041 - Pygmaioi

### Content Type

DeepDungeon

### What threat level sould the mob have

Easy

### What agro type does the mob have

None

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

**Comment by wolfcomp** [comment]
Seems to be related to #203 as it has the data in the files.
