### ISSUE TITLE
Mimic - After Pomander of Alteration

### ISSUE THREAD

**Issue by HumonGousPhil** [wolfcomp/MonsterDex#207]
### Mob Id

2566 - Mimic

### Content Type

DeepDungeon

### What threat level sould the mob have

Caution

### What agro type does the mob have

Proximity

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

**Comment by wolfcomp** [comment]
Seems to be related to #203 as it has the data in the files.
