### ISSUE TITLE
POTD Floor 150-160 Mimic

### ISSUE THREAD

**Issue by Krawller** [wolfcomp/MonsterDex#211]
### Mob Id

2566 - Mimic

### Content Type

DeepDungeon

### What threat level sould the mob have

Caution

### What agro type does the mob have

Proximity

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

### Additional mob text guide

Curse can be interrupted

**Comment by wolfcomp** [comment]
Seems to be related to #203 as it has the data in the files.
