### ISSUE TITLE
mob missing data 12223 eureka orthos

### ISSUE THREAD

**Issue by Benedictum** [wolfcomp/MonsterDex#214]
### Mob Id

12223 - Orthodrone

### Content Type

DeepDungeon

### What threat level sould the mob have

Caution

### What agro type does the mob have

Proximity

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

### Additional mob text guide

frontal line aoe

**Comment by wolfcomp** [comment]
Fixed
